### ISSUE TITLE
Stop Event Propagation onClick

### ISSUE THREAD

**Issue by ghost** [darianstlex/react-sm-select#2]
Thanks for this awesome react select library, i really enjoy using it. Unfortunately, when clicking on the header to open the dropdown, the event is bubbling up, causing to trigger another event in my application. When capturing the onClick-event, the dropdown does not open anymore. Using the key-down/up works just fine. I had a quick look into the src. Could it be possible to change the onClick behaviour in the MultiSelect class:

`onClick={() => this.toggleDropDown()}`

to make it similar to the behaviour when pressing the keys?

Thanks!

**Comment by darianstlex** [comment]
Hi, thanks for the quick solution, will try to fix it in the next few days

**Comment by darianstlex** [comment]
The PR is done, can you check if this fix is working for you pls: `bug/fix-click-propagation` #3 
Also thinking to make it optional
Add `stopClickPropagation`

Thanks

**Comment by darianstlex** [comment]
Closing it, as it seems it's not needed anymore if so, reopen

**Comment by ghost** [comment]
Sorry for delay. I've just checked the PR and it works like a charm.

Thank you very much.

**Comment by darianstlex** [comment]
released: 1.0.8
