### ISSUE TITLE
IE11/Edge automatically closing the dropdown on a selection

### ISSUE THREAD

**Issue by Trinitonn** [darianstlex/react-sm-select#4]
Hi Ivan, thank you so much for sharing this great work with us!

I'm not sure if this is a bug or a feature, because I don't know how it's intended to work;
When using IE 11/Edge, the dropdown closes after a selection. In Chrome the dropdown stays open, which makes it easier to choose multiple options.

To reproduce, just use the [playground](https://darianstlex.github.io/react-sm-select/#/playground/playground) with default settings.

I would be glad if you could consider to make this an option, or - if your intention is that the popup should stay open, perhaps you have some time to check it out. Thanks! 🥇

**Comment by darianstlex** [comment]
Hi Trinitonn, thank you for the feedback, this looks like a bug, unfortunately, I don't have a windows machine, so it might take some time to be fixed.

**Comment by Trinitonn** [comment]
Hi again, i opened a pull request to fix this issue, #5.

Feel free to have a look and implement your own fix (or mine). Actually, when I have a second look at this, maybe the eventPath function is unnecessary? Just checking on this.mouseIsHover and !this.isSingle() is enough (haven't tested this though)

**Comment by darianstlex** [comment]
sorry for the delay, you are right, just hover seems enough to detect the click, v1.0.9

**Comment by Trinitonn** [comment]
Hi, thanks for the update. Downloaded 1.0.9 now, and it works like a charm in IE.
