### ISSUE TITLE
Custom Icon in option list 

### ISSUE THREAD

**Issue by mdmusaib** [darianstlex/react-sm-select#8]
instead of checkbox, I would love to have a custom icon in option list. please update the feature and do a needful  and oblige..

**Comment by darianstlex** [comment]
hi, so instead of a check box, you want to be able to replace it with 2 icons (checked/unchecked)?

**Comment by darianstlex** [comment]
check this: https://darianstlex.github.io/react-sm-select/#/spec/custom - Option Custom Icon
this is just a quick example, you can create any custom option component, let me know if this is not what you need

**Comment by mdmusaib** [comment]
Thank you very much for a quick response......

**Comment by darianstlex** [comment]
reopen if needed
