### ISSUE TITLE
customize the value in react-sm-select

### ISSUE THREAD

**Issue by mdmusaib** [darianstlex/react-sm-select#9]
Hi, 
I would like to have a both label and value in the value props, 
If user selects the options it should be embed both label and value of the selected option in the input....

eg:
In options like 1}apple-Apple,2}mango-Mango, 3}orange-Orange in the dropdown, suppose user select option 1 means in the input also it should come like this apple-Apple not just **Apple**(only Value)

**Comment by darianstlex** [comment]
Hi, unfortunately, this change is not backwards compatible, also its easy to get whatever you need from the options having the selected option/value
